# Generated by Django 5.2.1 on 2025-05-27 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('id_comp', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('datetime_comp', models.DateTimeField()),
                ('total_comp', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': ['compra'],
                'verbose_name_plural': ['compras'],
                'ordering': ['id_comp'],
            },
        ),
        migrations.CreateModel(
            name='Pedidos_Proveedores',
            fields=[
                ('id_pedi_prov', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('state_pedi_prov', models.CharField(max_length=100)),
                ('date_pedi_prov', models.DateField()),
            ],
            options={
                'verbose_name': ['pedido a proveedor'],
                'verbose_name_plural': ['pedidos_a_proveedores'],
                'ordering': ['id_pedi_prov'],
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id_prod', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('type_prod', models.CharField(max_length=100)),
                ('dateReg_prod', models.DateField()),
                ('descr_prod', models.CharField(max_length=500)),
                ('brand_prod', models.CharField(max_length=100)),
                ('bar_cod_prod', models.CharField(max_length=50)),
                ('active_prod', models.BooleanField()),
                ('name_prod', models.CharField(max_length=100)),
                ('unitaryprice_prod', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            options={
                'verbose_name': ['producto'],
                'verbose_name_plural': ['productos'],
                'ordering': ['id_prod'],
            },
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id_prov', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('name_prov', models.CharField(max_length=100)),
                ('active_prov', models.BooleanField()),
                ('registered_name_prov', models.CharField(max_length=100)),
                ('phone_prov', models.CharField(max_length=20)),
                ('mail_prov', models.EmailField(max_length=254)),
                ('cuit_prov', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': ['proveedor'],
                'verbose_name_plural': ['proveedores'],
                'ordering': ['id_prov'],
            },
        ),
        migrations.CreateModel(
            name='Detalle_Pedidos_Proveedores',
            fields=[
                ('id_det_ped_prov', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('cantidad_det_ped_prov', models.PositiveIntegerField()),
                ('precio_unitario_det_ped_prov', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control_compras.pedidos_proveedores')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control_compras.productos')),
            ],
            options={
                'verbose_name': ['detalle_de_pedido_a_proveedor'],
                'verbose_name_plural': ['detalles_de_pedido_a_proveedores'],
                'ordering': ['id_det_ped_prov'],
            },
        ),
        migrations.CreateModel(
            name='Detalle_Compras',
            fields=[
                ('id_det_comp', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('cant_det_comp', models.IntegerField()),
                ('subtotal_det_comp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control_compras.compras')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control_compras.productos')),
            ],
            options={
                'verbose_name': ['detalle_de_compra'],
                'verbose_name_plural': ['detalles_de_compra'],
                'ordering': ['id_det_comp'],
            },
        ),
        migrations.AddField(
            model_name='productos',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control_compras.proveedores'),
        ),
        migrations.AddField(
            model_name='pedidos_proveedores',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control_compras.proveedores'),
        ),
        migrations.AddField(
            model_name='compras',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control_compras.proveedores'),
        ),
    ]
