# Generated by Django 5.2.1 on 2025-06-05 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control_compras', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalle_compras',
            name='compra',
        ),
        migrations.RemoveField(
            model_name='detalle_compras',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='detalle_pedidos_proveedores',
            name='pedido',
        ),
        migrations.RemoveField(
            model_name='detalle_pedidos_proveedores',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='pedidos_proveedores',
            name='proveedor',
        ),
        migrations.RemoveField(
            model_name='productos',
            name='proveedor',
        ),
        migrations.DeleteModel(
            name='Compras',
        ),
        migrations.DeleteModel(
            name='Detalle_Compras',
        ),
        migrations.DeleteModel(
            name='Detalle_Pedidos_Proveedores',
        ),
        migrations.DeleteModel(
            name='Pedidos_Proveedores',
        ),
        migrations.DeleteModel(
            name='Productos',
        ),
        migrations.DeleteModel(
            name='Proveedores',
        ),
    ]
