# Generated by Django 5.2.1 on 2025-06-05 16:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alertas',
            fields=[
                ('id_alert', models.AutoField(primary_key=True, serialize=False)),
                ('message_alert', models.CharField(max_length=200)),
                ('type_alert', models.CharField(max_length=100)),
                ('datetime_alert', models.DateTimeField()),
                ('read_alert', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Cajas',
            fields=[
                ('id_caja', models.AutoField(primary_key=True, serialize=False)),
                ('total_gastos_caja', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_vents_caja', models.DecimalField(decimal_places=2, max_digits=10)),
                ('datetime_open_caja', models.DateTimeField()),
                ('opening_mont_caja', models.DecimalField(decimal_places=2, max_digits=10)),
                ('closing_mont_caja', models.DecimalField(decimal_places=2, max_digits=10)),
                ('open_caja', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Ciudades',
            fields=[
                ('id_ciudad', models.AutoField(primary_key=True, serialize=False)),
                ('name_ciudad', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id_cli', models.AutoField(primary_key=True, serialize=False)),
                ('name_cli', models.CharField(max_length=200)),
                ('dni_cli', models.CharField(max_length=100)),
                ('mail_cli', models.EmailField(max_length=254)),
                ('phone_cli', models.CharField(max_length=100)),
                ('date_reg_cli', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('id_comp', models.AutoField(primary_key=True, serialize=False)),
                ('datetime_comp', models.DateTimeField()),
                ('total_comp', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Descuentos',
            fields=[
                ('id_desc', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_desc', models.CharField(max_length=100)),
                ('porcentaje_desc', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha_inicio_desc', models.DateField()),
                ('fecha_fin_desc', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Historial_Movimiento_Caja',
            fields=[
                ('id_histo_movi_caja', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_histo_movi_caja', models.DateTimeField(auto_now_add=True)),
                ('tipo_histo_movi_caja', models.CharField(choices=[('Ingreso', 'Ingreso'), ('Egreso', 'Egreso')], max_length=20)),
                ('montohisto_movi_caja', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion_histo_movi_caja', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Metodos_Pago',
            fields=[
                ('id_metpag', models.AutoField(primary_key=True, serialize=False)),
                ('name_metpag', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Pedidos_Proveedores',
            fields=[
                ('id_pedi_prov', models.AutoField(primary_key=True, serialize=False)),
                ('state_pedi_prov', models.CharField(max_length=100)),
                ('date_pedi_prov', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id_prod', models.AutoField(primary_key=True, serialize=False)),
                ('type_prod', models.CharField(max_length=100)),
                ('dateReg_prod', models.DateField()),
                ('descr_prod', models.CharField(max_length=500)),
                ('brand_prod', models.CharField(max_length=100)),
                ('bar_cod_prod', models.CharField(max_length=50)),
                ('active_prod', models.BooleanField()),
                ('name_prod', models.CharField(max_length=100)),
                ('unitaryprice_prod', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id_prov', models.AutoField(primary_key=True, serialize=False)),
                ('name_prov', models.CharField(max_length=100)),
                ('active_prov', models.BooleanField()),
                ('registered_name_prov', models.CharField(max_length=100)),
                ('phone_prov', models.CharField(max_length=20)),
                ('mail_prov', models.EmailField(max_length=254)),
                ('cuit_prov', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Provincias',
            fields=[
                ('id_provin', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_provincia', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario_Roles',
            fields=[
                ('id_usuario_rol', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Calles',
            fields=[
                ('id_calle', models.AutoField(primary_key=True, serialize=False)),
                ('name_calle', models.CharField(max_length=100)),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.ciudades')),
            ],
        ),
        migrations.CreateModel(
            name='Direcciones',
            fields=[
                ('id_direccion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_direccion', models.CharField(max_length=100)),
                ('departamento_direccion', models.CharField(max_length=100)),
                ('referecia_direccion', models.CharField(max_length=100)),
                ('calle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.calles')),
            ],
        ),
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id_emple', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_emple', models.CharField(max_length=100)),
                ('direccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.direcciones')),
            ],
        ),
        migrations.CreateModel(
            name='Pedidos_Clientes',
            fields=[
                ('id_pedi_cli', models.AutoField(primary_key=True, serialize=False)),
                ('state_pedi_cli', models.CharField(max_length=100)),
                ('date_pedi_cli', models.DateField()),
                ('cantidad_pedido_cli', models.IntegerField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.clientes')),
            ],
        ),
        migrations.CreateModel(
            name='Producto_En_Descuento',
            fields=[
                ('id_prod_desc', models.AutoField(primary_key=True, serialize=False)),
                ('descuento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.descuentos')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.productos')),
            ],
        ),
        migrations.CreateModel(
            name='Prod_Vencido',
            fields=[
                ('id_prod_venc', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_venc', models.DateField()),
                ('cantidad_venc', models.PositiveIntegerField()),
                ('motivo_venc', models.CharField(default='Vencimiento', max_length=100)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.productos')),
            ],
        ),
        migrations.CreateModel(
            name='Historial_Precio_Producto',
            fields=[
                ('id_histo_precio_prod', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('precio_anterior_histo_precio_prod', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_nuevo_histo_precio_prod', models.DecimalField(decimal_places=2, max_digits=10)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.productos')),
            ],
        ),
        migrations.CreateModel(
            name='Detalle_Pedidos_Proveedores',
            fields=[
                ('id_det_ped_prov', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_det_ped_prov', models.PositiveIntegerField()),
                ('precio_unitario_det_ped_prov', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.pedidos_proveedores')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.productos')),
            ],
        ),
        migrations.CreateModel(
            name='Detalle_Pedidos_Clientes',
            fields=[
                ('id_det_ped_cli', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_det_ped_cli', models.PositiveIntegerField()),
                ('observaciones_det_ped_cli', models.TextField(blank=True, null=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.pedidos_clientes')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.productos')),
            ],
        ),
        migrations.CreateModel(
            name='Detalle_Compras',
            fields=[
                ('id_det_comp', models.AutoField(primary_key=True, serialize=False)),
                ('cant_det_comp', models.IntegerField()),
                ('subtotal_det_comp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.compras')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.productos')),
            ],
        ),
        migrations.AddField(
            model_name='productos',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.proveedores'),
        ),
        migrations.AddField(
            model_name='pedidos_proveedores',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.proveedores'),
        ),
        migrations.AddField(
            model_name='compras',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.proveedores'),
        ),
        migrations.AddField(
            model_name='ciudades',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.provincias'),
        ),
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('id_stock', models.AutoField(primary_key=True, serialize=False)),
                ('cant_before_stock', models.IntegerField()),
                ('cant_after_stock', models.IntegerField()),
                ('datetime_stock', models.DateTimeField()),
                ('reasonchange_stock', models.CharField(max_length=200)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.productos')),
            ],
        ),
        migrations.CreateModel(
            name='Historial_Stock',
            fields=[
                ('id_histo_stock', models.AutoField(primary_key=True, serialize=False)),
                ('typemove_histo_stock', models.CharField(max_length=100)),
                ('cantmove_histo_stock', models.CharField(max_length=100)),
                ('reasonmove_histo_stock', models.CharField(max_length=100)),
                ('datetime_histo_stock', models.DateTimeField()),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.stocks')),
            ],
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id_vent', models.AutoField(primary_key=True, serialize=False)),
                ('total_vent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('datetime_vent', models.DateTimeField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.clientes')),
            ],
        ),
        migrations.CreateModel(
            name='Vent_MetPag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('monto_xvmp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodopago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.metodos_pago')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.ventas')),
            ],
        ),
        migrations.CreateModel(
            name='Puntos_Cliente',
            fields=[
                ('id_puntos_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('puntos_obtenidos', models.PositiveIntegerField()),
                ('fecha_points', models.DateField(default=django.utils.timezone.now)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.clientes')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.ventas')),
            ],
        ),
        migrations.CreateModel(
            name='Detalle_Ventas',
            fields=[
                ('id_det_vent', models.AutoField(primary_key=True, serialize=False)),
                ('cant_det_vent', models.IntegerField()),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.productos')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.ventas')),
            ],
        ),
    ]
