# Generated by Django 5.2.1 on 2025-05-26 22:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=100)),
                ('fecha_registro', models.DateField(default=django.utils.timezone.now)),
                ('descripcion', models.CharField(max_length=500)),
                ('marca', models.CharField(max_length=100)),
                ('codigo_barras', models.CharField(max_length=50)),
                ('activo', models.BooleanField(default=True)),
                ('nombre', models.CharField(max_length=100)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
